### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by igobythisname** [LorenzoPane/browserdefault#11]
Hi. Thank you for your genius that is BrowserDefault! I have it set to Google Chrome, however, when I open links in GMail app, my device crashes. I think my GMail is previously set to open in Chrome and this might be conflicting / causing the crash. Thanks!

**Comment by LorenzoPane** [comment]
What version are you on?

**Comment by igobythisname** [comment]
XS Max iOS 12.1.1 Chimera 1.0.4
BrowserDefault 1.8.0

**Comment by LorenzoPane** [comment]
This should be fixed in 1.8.2.  You can download it https://github.com/LorenzoPane/browserdefault/blob/master/StableBuilds/com.lpane.browserdefault_1.8.2_iphoneos-arm.deb, or wait for it to be released on Packix within the next day or so.

**Comment by igobythisname** [comment]
I am aware that 1.8.1 is the current version but I don't see any notes about the bug in the changelog so I commented here first

**Comment by igobythisname** [comment]
Oh awesome! You are great! Thanks for all your hard work, your quick response. Keep up the hard work. Thanks! :D

**Comment by LorenzoPane** [comment]
Let me know if it is fixed.

**Comment by igobythisname** [comment]
Thanks for the link! I installed 1.8.2, device still crashing. I was able to change Gmail settings "open browser in" to Safari (instead of Chrome) and it's no longer crashing...

**Comment by LorenzoPane** [comment]
Damn.  Let me download gmail and take a look.
